### PR TITLE
feat: unread message indicator in page title

### LINKED ISSUE #124: Unread indicators in title
A lot of online chat platforms make use of the tab title to indicate to users that there are unread messages by means of a little `(1)` at the start of the title, and sometimes also a little red dot in the favicon. Having a similar feature on KB would potentially make it easier for users who want to make use of KB for text-based chat while also doing something else at the same time.

### PR DESCRIPTION
**Pull request by RegsonDR**
Resolves #124 

but waiting on a fix for #132 for it to be working as intended

### CODE REVIEW

**Comment by amishshah** [comment]
This only seems to work if the chats page is loaded, could you move the Helmet code to somewhere closer to the root of the app?

**Review by amishshah — CHANGES_REQUESTED** [review]
This only seems to work if the chats page is loaded, could you move the Helmet code to somewhere closer to the root of the app?

**Comment by RegsonDR** [comment]
@amishshah 
I have moved this up to AutoAppBar as it's rendered on every page, would this be the most ideal place?

I have also noticed that when the app is initially loaded on the homepage, no unread indicators are set when messages are sent until you click onto one of the other pages, then unread indicators work whatever page you are on. However, when you load the app on one of the other pages, unread indicators are immediately set when messages are sent. I'm not exactly sure what is loaded on the protected routes differently from the homepage to cause this difference. Probably should be a separated issue. Happy to jump onto a call to discuss it further if it's not clear.

**Review by amishshah — APPROVED** [review]

**Comment by amishshah** [comment]
> @amishshah
> I have moved this up to AutoAppBar as it's rendered on every page, would this be the most ideal place?
> 
> I have also noticed that when the app is initially loaded on the homepage, no unread indicators are set when messages are sent until you click onto one of the other pages, then unread indicators work whatever page you are on. However, when you load the app on one of the other pages, unread indicators are immediately set when messages are sent. I'm not exactly sure what is loaded on the protected routes differently from the homepage to cause this difference. Probably should be a separated issue. Happy to jump onto a call to discuss it further if it's not clear.

At the moment, this makes sense since the channels data is only fetched when the user visits the chats page. If the page hasn't been visited, then the notifications will not generate properly - I'll make a separate issue for this!

**Pull request merged**
