### PR TITLE
feat: chat page design

### LINKED ISSUE #21: Chat interface

### LINKED ISSUE #25: Chat bubbles
Design the chat bubbles

### PR DESCRIPTION
**Pull request by amishshah**
Resolves #21 and resolves #25 

This PR adds a non-functional design for the chats page. It's still missing the column for user/event info the right, but this PR is already quite large and I'd rather add that in a separate PR. 

### Screenshots

image

### CODE REVIEW

**Comment by zainja** [comment]
looks great, very beautiful 
some suggestions:
the top bar is a bit crowded in the phone version I don't think it is necessary to have a logout button
the input text we could use this variant
  <TextField id="outlined-basic" label="Outlined" variant="outlined" />
which is the all rounded version of the one you used
image

**Review by HishamAlyahya — CHANGES_REQUESTED** [review]
That looks fantastic man!

Some comments:
When the user's using a phone the drawer should automatically collapse when they tap on a channel.

The profile pic/name above the messages would look really messy and clunky when the messages alternate between different senders in event channels. Maybe a style similar to Messenger's would work more nicely?

Also, there should probably be an initial thing to display when the user first navigates to the chat page. Maybe extend the drawer so that it takes up the width of the screen and only show the chat panel when the user clicks on a channel?

**Comment by amishshah** [comment]
> looks great, very beautiful
> some suggestions:
> the top bar is a bit crowded in the phone version I don't think it is necessary to have a logout button
> the input text we could use this variant
> 
> which is the all rounded version of the one you used
> image

Yeah I really wanted to use this but I put a slight background on that bar and for some reason the textbox is transparent so you could see the background through the textbox :( When I tried to add a background to it the background extended outside the rounded corners so it looked weird.

I agree this would look better though, just not sure how to do it yet. We could make an issue for it and take a look at it another time?

**Comment by amishshah** [comment]
> That looks fantastic man!
> 
> Some comments:
> When the user's using a phone the drawer should automatically collapse when they tap on a channel.
> 
> The profile pic/name above the messages would look really messy and clunky when the messages alternate between different senders in event channels. Maybe a style similar to Messenger's would work more nicely?
> 
> Also, there should probably be an initial thing to display when the user first navigates to the chat page. Maybe extend the drawer so that it takes up the width of the screen and only show the chat panel when the user clicks on a channel?

These are all great suggestions! Will work on them tomorrow :+1:

**Comment by amishshah** [comment]
> looks great, very beautiful
> some suggestions:
> the top bar is a bit crowded in the phone version I don't think it is necessary to have a logout button
> the input text we could use this variant
> 
> which is the all rounded version of the one you used
> image

Also about the logout button, I agree and this is discussed more in #34. It's out of the scope of this PR imo.

**Comment by amishshah** [comment]
### Changes made

- Clicking a channel on mobile closes the channel drawer
- Added a background to the chat from graphics team
- On desktop, the channel drawer is no longer toggleable. This was because of animation performance issues after adding the background.
- Added a screen when no channel is selected

Didn't address this:

> The profile pic/name above the messages would look really messy and clunky when the messages alternate between different senders in event channels. Maybe a style similar to Messenger's would work more nicely?

I agree with it, but maybe we could make this a separate good first issue for someone new to React to work on maybe?

### Screenshots:

image

image

**Review by HishamAlyahya — COMMENTED** [review]
One thing (and I'm nitpicking here), I think it'd be better for the drawer to automatically expand when a phone user first navigates to the chat page.
Other than that, looks great!

**Comment by amishshah** [comment]
> One thing (and I'm nitpicking here), I think it'd be better for the drawer to automatically expand when a phone user first navigates to the chat page.
> Other than that, looks great!

@HishamYahya  Done!

**Review by HishamAlyahya — APPROVED** [review]
Looks good!

**Pull request merged**
