### PR TITLE
feat: implemented routing and initialised page components

### PR DESCRIPTION
**Pull request by HishamAlyahya**

### CODE REVIEW

**Review by amishshah — CHANGES_REQUESTED** [review]
Could you remove the now-unused App.css? And also end the new `tsx` files with a new line?

**Review by amishshah — CHANGES_REQUESTED** [review]
Actually looking at this again, could you refactor each page to use a class-based approach instead? i.e. each page is a component extending `React.Component`? We would have to do this at some point, so might as well do it now

**Comment by HishamAlyahya** [comment]
Oh yeah about that, are we not going to be using hooks anywhere in the app then? I figure it might be a good idea to stick to either the class based or the hook approach for all stateful components. Thoughts?

**Comment by amishshah** [comment]
@HishamYahya ah that's fine then!

**Pull request merged**
